---
- name: Update package cache and install install soft
  block:
    - name: Add Node.js repository
      shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      args:
        warn: false
      when: ansible_distribution == "Ubuntu"
    
    - name: Check last modification time of apt cache
      ansible.builtin.stat:
        path: /var/cache/apt/pkgcache.bin
      register: cache_stat
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache (apt/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when:
        - ansible_distribution == "Ubuntu"
        - (ansible_date_time.epoch | int - cache_stat.stat.mtime) > 300

    - name: Install Node.js and npm
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
    
    - name: Install http-server npm package globally
      ansible.builtin.command:
        cmd: npm install http-server -g
  become: true
