---
- name: Create systemd unit file and start the service
  block:
    - name: Create systemd unit file
      template:
        src: frontend_unit_file.j2
        dest: /etc/systemd/system/{{ service_name }}

    - name: Start created service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        daemon_reload: true
        state: started
        enabled: true
  become: true
