stages:
  - release
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

upload-helm:
  stage: release
  image: alpine/k8s:1.27.13
  script:
    - helm package --version $VERSION sausage-store-chart/
    - curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file sausage-store-${VERSION}.tgz ${NEXUS_REPO_URL}/sausage-store-${VERSION}.tgz

deploy-helm:
  stage: deploy
  image: alpine/k8s:1.27.13
  environment:
    name: test/helm
    url: $STORE_URL
  before_script:
    - mkdir -p ~/.kube
    - echo $KUBECONF | base64 -d > ~/.kube/config
    - helm version
    - cat values.yaml
    - envsubst < values.yaml > values.tmp && mv values.tmp values.yaml
    - cat values.yaml
    # - envsubst < ./backend-report/secrets.yaml > ./backend-report/secrets.tmp && mv ./backend-report/secrets.tmp ./backend-report/secrets.yaml
  script:
    - helm repo add nexus $NEXUS_REPO_URL --username $NEXUS_REPO_USER --password $NEXUS_REPO_PASS
    - helm repo update
    - helm repo list
    - helm search repo nexus
    - echo ${KUBE_DOCKER_REGISTRY}
    - helm upgrade --install sausage-store
      --set secrets.springDatasourceUsername=${KUBE_SPRING_DATASOURCE_USERNAME}
      --set secrets.springDatasourcePassword=${KUBE_SPRING_DATASOURCE_PASSWORD}
      --set secrets.mongoUser=${KUBE_MONGO_USER}
      --set secrets.mongoPassword=${KUBE_MONGO_PASSWORD}
      --set secrets.mongoHost=${KUBE_MONGO_HOST}
      --set secrets.mongoDatabase=${KUBE_MONGO_DATABASE}
      --set fqdn="std-027-58.k8s.praktikum-services.tech"
      --atomic --timeout 15m
      nexus/sausage-store
  after_script:
    - rm ~/.kube/config
