#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ansible

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: ansible
    gecos: ansible
    shell: /bin/bash
    primary_group: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
