---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  labels:
    app: {{ .Release.Name }}-frontend-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{.Values.name}}
