---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  revisionHistoryLimit: 12
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-027-58/sausage-store/sausage-backend:1.0.1330498
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://rc1a-po1jnu39i5wfa4bw.mdb.yandexcloud.net:6432/std-027-58?ssl=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dbs
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbs
                  key: SPRING_DATASOURCE_PASSWORD
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: dbs
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbs
                  key: MONGO_PASSWORD
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: dbs
                  key: MONGO_HOST
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dbs
                  key: MONGO_DATABASE
            # - name: SPRING_DATA_MONGODB_URI
            #   value: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27018/${MONGO_DATABASE}?tls=true"
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
