---
apiVersion: v1
kind: Secret
metadata:
  name: dbs
  labels:
    app: dbs
data:
  SPRING_DATASOURCE_USERNAME: c3RkLTAyNy01OA==
  SPRING_DATASOURCE_PASSWORD: VGVzdHVzcjEyMzQ=
  MONGO_USER: c3RkLTAyNy01OA==
  MONGO_PASSWORD: VGVzdHVzcjEyMzQ=
  MONGO_HOST: cmMxYS1qenJmMmJydGo0aGhidmF4Lm1kYi55YW5kZXhjbG91ZC5uZXQ=
  MONGO_DATABASE: c3RkLTAyNy01OA==
type: Opaque

# Секрет, необходимый, чтобывзаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsiYXV0aCI6ImJXRnBibDl3ZFd4c09saEdjRFV4Y0dKNVUwUnVMVk5MUTBoNFFXUk4ifX19
type: kubernetes.io/dockerconfigjson
