---
apiVersion: v1
kind: Secret
metadata:
  name: dbs
  labels:
    app: dbs
data:
  SPRING_DATASOURCE_USERNAME: ${KUBE_SPRING_DATASOURCE_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${KUBE_SPRING_DATASOURCE_PASSWORD}
  MONGO_USER: ${KUBE_MONGO_USER}
  MONGO_PASSWORD: ${KUBE_MONGO_PASSWORD}
  MONGO_HOST: ${KUBE_MONGO_HOST}
  MONGO_DATABASE: ${KUBE_MONGO_DATABASE}
type: Opaque

# Секрет, необходимый, чтобывзаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ${KUBE_DOCKER_REGISTRY}
type: kubernetes.io/dockerconfigjson
