---
- name: Create systemd unit file
  template:
    src: backend_unit_file.j2
    dest: /etc/systemd/system/{{ service_name }}
  become: true

# - name: Force systemd to reread configs
#   ansible.builtin.systemd:
#     daemon_reload: true
#   become: true

- name: Create service log file
  become: true
  ansible.builtin.file:
    path: { { service_log_file } }
    state: touch
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: "0755"

- name: Start created service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    daemon_reload: true
    state: started
    enabled: true
