---
- name: Create systemd unit file, service log file and start the service
  block:
    - name: Create systemd unit file
      template:
        src: backend_unit_file.j2
        dest: /etc/systemd/system/{{ service_name }}
      
    - name: Create service log directory
      ansible.builtin.file:
        path: "/opt/log"
        state: directory
        mode: "0755"
    
    - name: Create service log file
      ansible.builtin.file:
        path: "{{ service_log_file }}"
        state: touch
        owner: "{{ service_user }}"
        group: "{{ service_user }}"
        mode: "0755"
    
    - name: Start created service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        daemon_reload: true
        state: started
        enabled: true
  become: true