---
apiVersion: v1
kind: Secret
metadata:
  name: dbs
  labels:
    app: dbs
data:
  SPRING_DATASOURCE_USERNAME: {{.Values.springDatasourceUsername}}
  SPRING_DATASOURCE_PASSWORD: {{.Values.springDatasourcePassword}}
  MONGO_USER: {{.Values.mongoUser}}
  MONGO_PASSWORD: {{.Values.mongoPassword}}
  MONGO_HOST: {{.Values.mongoHost}}
  MONGO_DATABASE: {{.Values.mongoDatabase}}
type: Opaque

# Секрет, необходимый, чтобывзаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsiYXV0aCI6ImJXRnBibDl3ZFd4c09saEdjRFV4Y0dKNVUwUnVMVk5MUTBoNFFXUk4ifX19
type: kubernetes.io/dockerconfigjson
