---
apiVersion: v1
kind: Secret
metadata:
  name: dbs
  labels:
    app: dbs
data:
  SPRING_DATASOURCE_USERNAME: {{.Values.springDatasourceUsername}}
  SPRING_DATASOURCE_PASSWORD: {{.Values.secrets.springDatasourcePassword}}
  MONGO_USER: {{.Values.secrets.mongoUser}}
  MONGO_PASSWORD: {{.Values.secrets.mongoPassword}}
  MONGO_HOST: {{.Values.secrets.mongoHost}}
  MONGO_DATABASE: {{.Values.secrets.mongoDatabase}}
type: Opaque

# Секрет, необходимый, чтобывзаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    {{.Values.secrets.kubeDockerRegistry}}
type: kubernetes.io/dockerconfigjson
