---
apiVersion: v1
kind: Secret
metadata:
  name: dbs
  labels:
    app: dbs
data:
  SPRING_DATASOURCE_USERNAME:
    {{.Values.global.secrets.springDatasourceUsername | b64enc}}
  SPRING_DATASOURCE_PASSWORD:
    {{.Values.global.secrets.springDatasourcePassword | b64enc}}
  MONGO_USER: {{.Values.global.secrets.mongoUser | b64enc}}
  MONGO_PASSWORD: {{.Values.global.secrets.mongoPassword | b64enc}}
  MONGO_HOST: {{.Values.global.secrets.mongoHost | b64enc}}
  MONGO_DATABASE: {{.Values.global.secrets.mongoDatabase | b64enc}}
type: Opaque

# Секрет, необходимый, чтобывзаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: {{.Values.global.secrets.kubeDockerRegistry | b64enc}}
type: kubernetes.io/dockerconfigjson
