---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
  labels:
    app: {{ .Release.Name }}-backend-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{.Values.name}}
