---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{.Release.Namespace}}
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
    route:
       group_by: [alertname, app]
       group_wait: 10s
       group_interval: 30s
       repeat_interval: 30m
       receiver: "telegram"
       routes:
         - receiver: "telegram"
           group_wait: 10s
           match_re:
             severity: critical|warning
           continue: true
    receivers:
     - name: "telegram"
       telegram_configs:
         - send_resolved: true
           bot_token: {{ .Values.bot_token }}
           chat_id: {{ .Values.chat_id }}
           message: |-
             {{ "{{" }}  range .Alerts {{ "}}" }}{{ "{{" }} .Status | toUpper {{ "}}" }}
             Severity: {{ "{{" }} .Labels.severity {{ "}}" }}
             Description: {{ "{{" }} .Annotations.description {{ "}}" }}
             Summary: {{ "{{" }} .Annotations.summary {{ "}}" }}
             Pod name: {{ "{{" }} .Labels.kubernetes_pod_name {{ "}}" }}{{ "{{" }} end {{ "}}" }}
